// Auto-generated by agency-pipeline for Barrie Good Plumbing Ltd
// Lead source: google_places · scraped 2026-04-30

export interface SiteConfig {
  business: {
    name: string;
    shortName?: string;
    tagline: string;
    established: string;
    owner: string;
    ownerRole: string;
    phone: string;
    phoneRaw: string;
    email: string;
    address: { street: string; city: string; state: string; zip: string };
    hours: Array<{ day: string; hours: string }>;
    license: string;
    insurance: string;
    tripFee: string;
    areasServed: string[];
  };
  trustBar: Array<{ label: string; detail?: string }>;
  hero: { eyebrow: string; headline: string; body: string; primaryCta: string; secondaryCta: string };
  services: Array<{ title: string; description: string }>;
  about: {
    eyebrow: string;
    headline: string;
    body: string[];
    bigStat: { value: string; label: string };
    stats: Array<{ value: string; label: string }>;
  };
  reviews: Array<{ name: string; location?: string; text: string; source: string }>;
  seo: { title: string; description: string };
}

export const siteConfig: SiteConfig = {
  "business": {
    "name": "Barrie Good Plumbing Ltd",
    "shortName": "Barrie Good Plumbing",
    "tagline": "Plumbing in Barrie, ON.",
    "established": "2022",
    "owner": "The team",
    "ownerRole": "Owner · Master Plumbing",
    "phone": "(647) 966-4296",
    "phoneRaw": "+16479664296",
    "email": "info@barriegoodplumbingltd.example",
    "address": {
      "street": "94 Copeman Crescent",
      "city": "Barrie",
      "state": "ON",
      "zip": "L4N 8B3"
    },
    "hours": [
      {
        "day": "Mon – Fri",
        "hours": "7:00 – 18:00"
      },
      {
        "day": "Saturday",
        "hours": "8:00 – 14:00"
      },
      {
        "day": "Sunday",
        "hours": "On call — emergency only"
      }
    ],
    "license": "Licensed",
    "insurance": "Fully insured",
    "tripFee": "Free estimates",
    "areasServed": [
      "Barrie",
      "Surrounding area"
    ]
  },
  "trustBar": [
    {
      "label": "Licensed · Insured"
    },
    {
      "label": "Est. 2022"
    },
    {
      "label": "5.0 ★ · 8 reviews"
    },
    {
      "label": "Same-day estimates"
    },
    {
      "label": "We answer the phone"
    }
  ],
  "hero": {
    "eyebrow": "Barrie · since 2022",
    "headline": "We answer the phone. We show up. We do the work.",
    "body": "Residential repairs, repipes, and small commercial in Barrie. Honest pricing, no upselling. The same crew shows up every time.",
    "primaryCta": "Call us",
    "secondaryCta": "Request an estimate"
  },
  "services": [
    {
      "title": "Repairs & emergencies",
      "description": "Leaks, slab leaks, burst pipes, water heaters out, drains backed up. Same-day response on weekdays."
    },
    {
      "title": "Repipes & rough-in",
      "description": "Whole-house repipes in PEX, copper, or CPVC. Renovation rough-in for additions and remodels."
    },
    {
      "title": "Water heaters",
      "description": "Tank, tankless, and hybrid installs and repairs. We stock the major brands so you're not waiting on parts."
    },
    {
      "title": "Drain cleaning",
      "description": "Snake, jet, and camera. We show you the footage so you know exactly what we found."
    },
    {
      "title": "Gas lines",
      "description": "New installs, leak repairs, and pressure tests for kitchens, pool heaters, and outdoor runs."
    },
    {
      "title": "Old-house plumbing",
      "description": "Galvanized pipe replacement, cast-iron sewer repairs, and the weird stuff older homes turn up."
    }
  ],
  "about": {
    "eyebrow": "The shop",
    "headline": "4 years of doing it right.",
    "body": [
      "We've been doing plumbing in Barrie since 2022. Family-run, fully licensed, fully insured.",
      "We answer our own phones, stock our own trucks, and don't sub anything out. The plumber who shows up is the plumber whose name is on the truck.",
      "We're not the cheapest plumber in town. We are the one you call when the last plumber said 'rip it out.'"
    ],
    "bigStat": {
      "value": "4+",
      "label": "Years serving the community"
    },
    "stats": [
      {
        "value": "4",
        "label": "Years in business"
      },
      {
        "value": "8",
        "label": "Google reviews · 5.0 ★"
      },
      {
        "value": "Yes",
        "label": "Licensed & insured"
      },
      {
        "value": "Same-day",
        "label": "Estimates"
      }
    ]
  },
  "reviews": [
    {
      "name": "M. H.",
      "location": "Barrie",
      "text": "Called on a Friday — they had someone out by Saturday morning, fixed it cleanly, fair price. The kind of plumber you tell your neighbours about.",
      "source": "Google"
    },
    {
      "name": "D. K.",
      "location": "Barrie",
      "text": "Showed up when they said they would, did exactly the work we asked for, and the price came in under the estimate. We'll be using them every time.",
      "source": "Google"
    },
    {
      "name": "J. L.",
      "location": "Barrie",
      "text": "Three other plumbers told us we needed a full replacement. These guys diagnosed the actual problem in 15 minutes. Saved us thousands.",
      "source": "Google"
    }
  ],
  "seo": {
    "title": "Barrie Good Plumbing Ltd — Plumbing in Barrie",
    "description": "Barrie Good Plumbing Ltd provides plumbing services in Barrie, ON. Residential repairs, repipes, and small commercial in Barrie. Honest pricing, no upselling. The same crew shows up every time."
  }
};
